spring.datasource.url=jdbc:mysql://103.150.125.181:3306/admin_taisan?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=admin_taisan
spring.datasource.password=ay8vzMGLnE
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

jwt.secret=${JWT_SECRET:day_la_cai_key_sieu_bao_mat_va_du_256_bit_nhe_em_trai}

server.port=${PORT:8081}